# FireworkManager Configuration file!
# @author syamn <admin@sakura-server.net>
# github: https://github.com/SakuraServer/FireworkManager

#====================#
#   General Config   #
#====================#
# nothing yet :3

#=====================#
#   Launch by Click   #
#=====================#
LaunchToolID: 293
CheckDistance: 300

#==================#
#   Vault Config   #
#==================#
# Use Vauld plugin
UseVault: false

#==================#
#   Debug Config   #
#==================#
Debug: false

#==================#
#   DO NOT TOUCH   #
#==================#
# Do not touch this option! It is a check if you are running the recent configuration version
ConfigVersion: 1